[package]
name = "backtalk"
version = "0.1.0"
authors = ["Robert Lord <robert@lord.io>"]

[dependencies]
futures = "0.1.9"
tokio-core = "0.1"
serde_json = "0.8.6"
queryst = "1"
hyper = { git = "https://github.com/hyperium/hyper", rev = "6eb07539214644fbcfff6e950bfbc688bf4764c2" }
